name: SUMC
favicon: null
layout_spectrum: 0.6119091974105686
typography_spectrum: 0.5419134316034615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3209110931493342
  lightness: 0.0955381034873426
  saturation: 0.8056327083613724
  rhythmicContrast: 0.08957344549708068
purpose: []
